version: "3.7"
services:

  db:
    image: postgres:13.4
    env_file: ./api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    env_file: ./api/.env
    ports:
      - "8090:8090"

  api:
    restart: always
    container_name: drf-api
    command : bash -c "python manage.py migrate &&
                       python manage.py loaddata initial_data.json &&
                       python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./api/.env
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command : yarn start
    container_name: react-app
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - api
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
